/******************************************************************************
 * Filename:       TESTING.h
 *
 * Description:    This file contains the TESTING service definitions and
 *                 prototypes.
 *
 *                 Generated by:
 *                 BDS version: 1.1.3139.0
 *                 Plugin:      Texas Instruments BLE SDK GATT Server plugin 1.0.9
 *                 Time:        Tue May 29 2018 02:48:00 GMT+02:00
 *

 * Copyright (c) 2015-2017, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

#ifndef _TESTING_H_
#define _TESTING_H_

#ifdef __cplusplus
extern "C"
{
#endif

/*********************************************************************
 * INCLUDES
 */
#include <bcomdef.h>

/*********************************************************************
 * CONSTANTS
 */
// Service UUID
#define TESTING_SERV_UUID 0x0B29
#define TESTING_SERV_UUID_BASE128(uuid) 0xD3, 0x7F, 0x21, 0x2C, 0xBC, 0xEE, 0xEE, 0x98, 0xF3, 0x4B, 0xD0, 0x79, LO_UINT16(uuid), HI_UINT16(uuid), 0x40, 0x37

// Steering Characteristic defines
#define T_STEERING_ID                 0
#define T_STEERING_UUID               0x1C1E
#define T_STEERING_UUID_BASE128(uuid) 0xD3, 0x7F, 0x21, 0x2C, 0xBC, 0xEE, 0xEE, 0x98, 0xF3, 0x4B, 0xD0, 0x79, LO_UINT16(uuid), HI_UINT16(uuid), 0x40, 0x37
#define T_STEERING_LEN                2
#define T_STEERING_LEN_MIN            2

// Speed Characteristic defines
#define T_SPEED_ID                 1
#define T_SPEED_UUID               0xA9B4
#define T_SPEED_UUID_BASE128(uuid) 0xD3, 0x7F, 0x21, 0x2C, 0xBC, 0xEE, 0xEE, 0x98, 0xF3, 0x4B, 0xD0, 0x79, LO_UINT16(uuid), HI_UINT16(uuid), 0x40, 0x37
#define T_SPEED_LEN                2
#define T_SPEED_LEN_MIN            2

/*********************************************************************
 * TYPEDEFS
 */

// Fields in characteristic "Steering"
//   Field "Value" format: sint16, bits: 16

// Fields in characteristic "Speed"
//   Field "Value" format: uint16, bits: 16

/*********************************************************************
 * MACROS
 */

/*********************************************************************
 * Profile Callbacks
 */

// Callback when a characteristic value has changed
typedef void (*TestingChange_t)( uint16_t connHandle, uint16_t svcUuid, uint8_t paramID, uint8_t *pValue, uint16_t len );

typedef struct
{
  TestingChange_t        pfnChangeCb;     // Called when characteristic value changes
  TestingChange_t        pfnCfgChangeCb;  // Called when characteristic CCCD changes
} TestingCBs_t;



/*********************************************************************
 * API FUNCTIONS
 */


/*
 * Testing_AddService- Initializes the Testing service by registering
 *          GATT attributes with the GATT server.
 *
 *    rspTaskId - The ICall Task Id that should receive responses for Indications.
 */
extern bStatus_t Testing_AddService( uint8_t rspTaskId );

/*
 * Testing_RegisterAppCBs - Registers the application callback function.
 *                    Only call this function once.
 *
 *    appCallbacks - pointer to application callbacks.
 */
extern bStatus_t Testing_RegisterAppCBs( TestingCBs_t *appCallbacks );

/*
 * Testing_SetParameter - Set a Testing parameter.
 *
 *    param - Profile parameter ID
 *    len   - length of data to write
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t Testing_SetParameter( uint8_t param, uint16_t len, void *value );

/*
 * Testing_GetParameter - Get a Testing parameter.
 *
 *    param - Profile parameter ID
 *    len   - pointer to a variable that contains the maximum length that can be written to *value.
              After the call, this value will contain the actual returned length.
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t Testing_GetParameter( uint8_t param, uint16_t *len, void *value );

/*********************************************************************
*********************************************************************/

#ifdef __cplusplus
}
#endif

#endif /* _TESTING_H_ */

